[metadata]
name = jenkins-jinny
version = 1.0.2
author = harhipova
author_email = annkapul@gmail.com
description =
license =
url =

[options]
packages = find:
python_requires = >=3.10
install_requires =
    click
    ipdb
    jmespath
    networkx
    parse
    requests
    python-jenkins>=1.8.2

[options.extras_require]
minimal =
full =
    pandas

[options.entry_points]
console_scripts =
    jenkins-jinny = jenkins_jinny.cli:start